spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100
logging:
  level:
    '[org.hibernate.orm.jdbc.bind]': trace
    '[com.linecorp.kotlinjdsl]': debug
