server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: gateway-service
  cloud:
    config:
      name: discovery,secret,r2dbc
  config:
    import:
      - configserver:${CONFIG_URL:http://localhost:8888}

springdoc:
  swagger-ui:
    urls:
      - name: core-service
        url: /v3/api-docs/core-service

logging:
  level:
    '[org.hibernate.orm.jdbc.bind]': trace
    '[com.linecorp.kotlinjdsl]': debug

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    '[org.hibernate.orm.jdbc.bind]': trace
    '[com.linecorp.kotlinjdsl]': debug
    '[com.netflix.discovery]': warn
    '[com.netflix.eureka]': warn
